### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by ghost** [ryu577/pyray#29]
pip install raypy

Ok.

ipython
import pyray

Result:
ModuleNotFoundError: No module named 'pyray'

**Comment by ryu577** [comment]
Thanks a lot for pointing out. I released a new version on pypy (0.0.1) and this seems to have fixed it. I used a virtual env to confirm. Can you please let me know if it works for you now?

**Comment by ghost** [comment]
It was fixed! I though it was my mistake before. Thank you very much!

**Comment by ryu577** [comment]
Great, I'll close the issue and thanks again for alerting.
