### ISSUE TITLE
render_scene_4d_axis Not Defined

### ISSUE THREAD

**Issue by hransom528** [ryu577/pyray#32]
I received this error when working on the examples, particularly with the best_plane_direction function:

`Traceback (most recent call last):
  File "animatedPlane.py", line 4, in <module>
    best_plane_direction(im_ind=i)
  File "C:\Users\hrans\AppData\Local\Programs\Python\Python37\lib\site-packages\pyray\shapes\plane.py", line 77, in best_plane_direction
    render_scene_4d_axis(draw, r1, 4, scale = scale, shift = shift)
NameError: name 'render_scene_4d_axis' is not defined`

It appears as though a function call could be calling a non-imported function from a lib.

**Comment by ryu577** [comment]
Thanks a lot for bringing this to my notice. I have fixed this by adding relevant imports. Also did some long overdue refactoring. If you try to install the library and try the examples now, they should work.
